proto/col_bool_safe.go

```
name                     old time/op    new time/op    delta
ColBool_DecodeColumn-32    23.7µs ± 1%    23.2µs ± 2%     ~     (p=0.095 n=5+5)
ColBool_EncodeColumn-32    28.0µs ± 2%    21.9µs ± 2%  -21.72%  (p=0.008 n=5+5)
name                     old speed      new speed      delta
ColBool_DecodeColumn-32  2.11GB/s ± 1%  2.16GB/s ± 2%     ~     (p=0.095 n=5+5)
ColBool_EncodeColumn-32  1.79GB/s ± 2%  2.28GB/s ± 2%  +27.73%  (p=0.008 n=5+5)
```
kudos to @cristaloleg

feat(col.bool): improve performance

---

internal/compress/compress.go
internal/compress/writer.go
query_test.go

fix(compress): ease block size limits

---

proto/col_auto.go
proto/col_auto_test.go

Please correct me about handling time zone.

Support ColumnTypeDateTime for auto result

---

proto/col_auto.go
proto/col_auto_test.go

* Rework ColAuto
* Add DataType field

feat(proto.auto): support DateTime64

---

internal/compress/reader.go
internal/compress/writer.go

feat(compress): reduce ZSTD encoder memory consumption

---

proto/date.go
proto/date32.go
proto/date32_test.go
proto/date_test.go

fix(proto): consider TZ in ToDate, ToDate32 helpers

---

.github/workflows/e2e.yml
.github/workflows/x.yml

ci: try go1.18 instead of go1.18.3

---

compress/writer.go

Fix ClickHouse/clickhouse-go#721

fix(compress): remove writer check for block size

---

proto/col_datetime64.go
proto/col_fixed_str.go
query_test.go

feat(proto): add missed Array() methods

---

client.go

During testing, @genzgd found that `ch-go` has issues with connecting to ClickHouse idle instances.
It happens due to the load balancer accepting connections, but waiting for an actual instance to handle the connection.
It breaks on a handshake packet received. The default proto operation timeout is 3s which is way too low to handle our use case. 
The solution is to provide an extra explicit `HandshakeTimeout` option with a default value of 5 minutes.

feat(connect): connect handshake timeout option (default 5m)

---

client.go

Fix for https://github.com/ClickHouse/ch-go/issues/231

fix: reset WriteDeadline

---

README.md

Hello, fixing wrong link. Awesome lib btw!

Fix link to benchmarks

---

proto/reader.go
query_test.go

fix(proto): remove utf8 check while decoding str

---

.github/workflows/e2e.yml

ci(e2e): update version list

---

README.md
internal/cmd/ch-native-dump/main.go
internal/cmd/ch-native-dump/test.sh
proto/dump_external_test.go

docs: add native dump example

---

client.go

fix(client): rework packet read timeouts

---

README.md

docs(readme): add enums section

---

proto/col_str.go

Try to batch prealloc/avoid append in ColStr.DecodeColumn for better perfomance on many small strings (so memory overhead not too high)
```
$ go test -benchmem -run=^$ -bench ^BenchmarkColStr_DecodeColumn$ github.com/ClickHouse/ch-go/proto
goos: linux
goarch: amd64
pkg: github.com/ClickHouse/ch-go/proto
cpu: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
BenchmarkColStr_DecodeColumn-6   	   31533	     38180 ns/op	 864.33 MB/s	       0 B/op	       0 allocs/op
PASS
ok  	github.com/ClickHouse/ch-go/proto	1.596s
$ benchcmp DecodeStr.txt DecodeStr2.txt 
benchmark                          old ns/op     new ns/op     delta
BenchmarkColStr_DecodeColumn-6     41783         38180         -8.62%
benchmark                          old MB/s     new MB/s     speedup
BenchmarkColStr_DecodeColumn-6     789.80 …
```

Prealloc in ColStr.DecodeColumn

---

.golangci.yml
client.go
otel_test.go
ping.go
proto/col_low_cardinality.go
query.go

Replace nil conn with explicit bool and reduce
possible NPE cases.
Ref: #301

fix(client): rework client close

---

proto/col_nullable.go
proto/col_nullable_test.go

fix(proto): fix Nullable.Or

---

.github/workflows/e2e.yml

ci: upd version list

---

README.md
examples/insert/main.go

docs: add LowCardinality(String) example

---

chpool/pool.go

The Pool should release the backgroundHealthCheck goroutine when chpool.Close is called.
Fix #1048 

fix(pool): goroutine leak in backgroundHealthCheck
