ClickHouse/ch-go

- cht/cht_test.go
- client.go
- client_test.go
It is not required to insert or select data.
Still available via ServerInfo.
> chore(client): don't parse server timezone

- proto/col_auto.go
- proto/col_auto_test.go
Support LowCardinality(String) for auto result. Test modified also.
> support LowCardinality(String) for auto result

- proto/col_low_cardinality.go
- proto/col_low_cardinality_raw.go
- proto/col_low_cardinality_raw_test.go
* Reset index as per #202
* Add back `ColLowCardinalityRaw` to possible lower-overhead column copy
> feat(proto): low cardinality improvements

- query.go
- query_test.go
We are doing same in clickhouse-go, so should be fine.
Fix #235
> fix: close connection after query cancellation

- chpool/pool.go
* pool.New method allows to skip connection test
* useful when connectivity problems are acceptable
> feat: create a pool without test connect

- proto/col_auto.go
- proto/col_auto_test.go
- proto/col_uuid.go
This PR adds a type inference for the UUID column. Maybe we should have made it with the code generator, but this will make this PR very difficult.
Closes #310
> chore: automatic column inference for the UUID column

- client.go
- proto/proto.go
Changes the protocol client name to `clickhouse/ch-go` and add the ability to extend that client name with a user supplied options.
> Client name

- proto/date32.go
- proto/date32_test.go
Change `Date32` representation to signed 32bit integer. Fixes issues with wrong data representation for Date32 for native format.
Resolves #319
> Fix Date32 overflow by changing its representation to int32

- proto/reader.go
Remove the hardcoded string length limit. Give the possibility to retrieve strings bigger than 10MB.
related to https://github.com/ClickHouse/clickhouse-go/issues/867
> fix(proto.reader): remove str length limit

- query.go
- query_test.go
A suggestion on how to resolve https://github.com/ClickHouse/ch-go/issues/382#issue-2146490836
With these changes, the totals row will be returned as the last row of the result.
- [V] Unit and integration tests covering the common scenarios were added
- [V] A human-readable description of the changes was provided to include in CHANGELOG
> fix(query): add with totals case (issue #382)

- proto/datetime.go
- proto/datetime64.go
- proto/datetime64_test.go
- proto/datetime_test.go
I use clickhouse-cli and clickhouse-go to execute the following SQL, but I get different results：
```
localhost :) select toDateTime('1970-01-01 00:00:00', 'UTC');
SELECT toDateTime('1970-01-01 00:00:00', 'UTC')
Query id: 1b43d122-7f5f-44fa-9f3b-4992bd305998
┌─toDateTime('1970-01-01 00:00:00', 'UTC')─┐
│                      1970-01-01 00:00:00 │
└──────────────────────────────────────────┘
1 row in set. Elapsed: 0.002 sec. 
```
```go
func main() {
conn, err := ConnectNative()
if err != nil {
panic((err))
}
query := "select toDateTime('1970-01-01 00:00:00', 'UTC')"
var rows driver.Rows
rows, _ = conn.Query(context.Background(), query)
for rows.Next() {
var ts time.Time
err = rows.Scan(&ts)
fmt.Println("ts", ts)
}
}
func ConnectNative() (driver.Conn, error) {
return …
```
> fix(proto): DateTime/DateTime64 with '1970-01-01 00:00:00 UTC'

- proto/date.go
- proto/date32.go
- proto/date32_test.go
- proto/date_test.go
https://github.com/ClickHouse/ch-go/issues/391
`time.Time`'s zero value when converted to Date and Date32 objects now equals 0 Unix time.
> Adds support for zero value time for date types.

- query.go
When the server closes the connection unexpectedly, the client will call cancelQuery (e.g. when client.packet fails). In client.cancelQuery, if client.flushBuf has data to flush, it will return a non-nil error and return early without calling conn.Close. This prevents the chpool from removing the client after client.Do and leaves the client.conn in a bad state such that future writes will always fail with a "broken pipe" error.
> fix(query): always close client.conn in cancelQuery (issue #405)

- client.go
In this PR I removed setting zero timeout in case of passed negative value.
The problem occurs when we call `client.Dial`:
1. Firstly [here](https://github.com/ClickHouse/ch-go/blob/main/client.go#L520) we call dial and sets default options, and when the `ReadTimeout` value is `NoTimeout`, we set it to zero.
2. Then, in `client.Connect` method, we call `opt.setDefault` as well [here](https://github.com/ClickHouse/ch-go/blob/main/client.go#L429), but by this moment `readTimeout` had been already set to default value zero, and here it would be interpreted as time duration zero value and be set to `DefaultReadTimeout`.
To prevent this error it is sufficient just to remove setting `ReadTimeout` to zero and leave it with negative value, because …
> Fix client default read timeout setting

- insert_bench_test.go
- proto/col_str.go
```
goos: linux
goarch: amd64
pkg: github.com/ClickHouse/ch-go
cpu: AMD Ryzen 9 5950X 16-Core Processor            
│    old.txt    │                new.txt                 │
│    sec/op     │    sec/op      vs base                 │
Insert/SmallColStr/Rows10000-32     2903.0µ ±  4%    634.0µ ±  8%   -78.16% (p=0.000 n=15)
Insert/SmallColStr/Rows100000-32    28.549m ±  2%    2.584m ± 13%   -90.95% (p=0.000 n=15)
Insert/SmallColStr/Rows1000000-32   172.39m ±  2%    27.35m ±  2%   -84.14% (p=0.000 n=15)
Insert/BigColStr/Rows10000-32        25.97m ± 17%    33.78m ± 10%   +30.07% (p=0.000 n=15)
Insert/BigColStr/Rows100000-32       375.0m ± 11%   1051.0m ± 41%  +180.22% (p=0.000 n=15)
geomean                              20.52m          13.16m         -35.87%
│    old.txt     │ …
```
> perf(proto): improve `ColStr` writing performance for small strings

- client.go
- client_test.go
In order to make exceptions testable with errors.Is, they must implement the `Unwrap` method to allow access to the underlying error code(s).
This change is addressing the problem of the below code not working as expected, when testing returned by `Do` method error:
c, _ := ch.Dial(ctx, ch.Options{...})
switch err := c.Do(ctx, ch.Query{...}); {
case err == nil:
// ...
case errors.Is(err, proto.ErrTableIsReadOnly), errors.Is(err, proto.ErrReadonly):
// ... <- Never executed, because exception unwraping is not implemented.
default:
// ...
}
Because `Exception` instances are created dynamically, unwrapping can ignore nested exception instances and collect only the underlying error codes.
> implement Exception.Unwrap method

- proto/col_auto.go
- proto/col_auto_test.go
- proto/column.go
[relevant docs](https://clickhouse.com/docs/en/sql-reference/data-types/decimal)
Infer `Decimal(P, S)` to its subtype. Ignore scale
> feat: infer Decimal

- .golangci.yml
- README.md
Also fix lint warning:
WARN [config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
> Fix typo in README

- cht/log.go
- cht/log_test.go
- proto/col_datetime64.go
- proto/col_enum.go
- proto/col_map.go
- proto/column.go
strings.Cut was added in 1.18: https://github.com/golang/go/issues/46336
> perf: use strings.Cut, also strings.IndexByte more

- proto/col_low_cardinality.go
the max key length should correlated with unique value length, but not row length.
> perf(col_low_cardinality): use small value.

- proto/column.go
- proto/column_test.go
1. `a,b=b,a` would leave `b==c`, always returning false
2. Decimal256 should not conflict with Decimal(76, 38)
3. propagate conflicts to inner types for Nullable/Array/LowCardinality
> fix: column type conflicts

- proto/column.go
- proto/column_test.go
Fixed regression caused by #435 (bisected to https://github.com/ClickHouse/ch-go/commit/ab04093adb55cfdfa960663ec03bac67162d151a)
> fix(proto): properly handle `Enum8` and `Enum8(...)` in conflicts checker

- proto/col_json_str.go
Small oversight from #1034, the underlying `ColStr` was not exported and could not be pre-allocated as needed.
```go
proto.ColJSONStr {
Str: proto.ColStr{
Buf: make([]byte, 0, strSize * bufferSize),
Pos: make([]proto.Position, 0, bufferSize),
}
}
```
This PR exports `Str` so the above code is possible
> fix: expose underlying string column for json

- compress/compress.go
- compress/compress_test.go
- compress/writer.go
Currently, the compress.Writer by default allocates 3 writers: zstd, lz4, and lz4hc. All of these allocate memory by default, and many times compressors are only created to be used for just one method, like in clickhouse-go driver https://github.com/ClickHouse/clickhouse-go/blob/main/conn.go#L76-L84
In particular, this line:
https://github.com/ClickHouse/ch-go/blob/f99ba048f6bf40cc2151576ca7a3ae3686303a2d/compress/writer.go#L87
allocates ~1MB, as internally it has 2 int hashtables with 65k size each:
https://github.com/pierrec/lz4/blob/1a4bbaef2f12f93c70060b52121e992756077a1f/internal/lz4block/block.go#L303-L308
Memory usage example using clickhouse-go with no compression configured:
> perf(compress.writer): allow creating a compress.writer with custom supported methods

- client.go
- compress/compress_test.go
- compress/fuzz_test.go
- compress/writer.go
- query.go
- server.go
#1039 included some code to reduce memory usage when initializing the compressor. After further review of ch-go and clickhouse-go, it seems only _ONE_ compression method is ever used per connection. With this in mind I have refactored and simplified the code.
The most important line of this PR is to actually _USE_ the optimization from #1039:
```go
compressor:  compress.NewWriter(compress.Level(opt.CompressionLevel), compressionMethod),
```
but in addition to this I have updated some functions and constants to reflect the actual usage patterns for compression.
`*Writer.Compress()` no longer takes a `Method` since this is known during initialization and does not change.
I don't believe this is a breaking change since these packages/constants are only used internally. The compression code …
> perf(compressor): reduce memory by using new compression code

- .gitignore
- compress/writer.go
Related - https://media.defcon.org/DEF%20CON%2032/DEF%20CON%2032%20presentations/DEF%20CON%2032%20-%20Paul%20Gerste%20-%20SQL%20Injection%20Isn%27t%20Dead%20Smuggling%20Queries%20at%20the%20Protocol%20Level.pdf
It is possible to smuggle query packet into the connection when a large amount of attacker controlled data can end up in the external data of query. If Compression: CompressionNone and this overflow occurs, the remainder of the external data is processed as native protocol bytes.
> fix(compressor): fixing an overflow that could potentially smuggle query in from data

- client.go
flush buf only reset buf if flush success.
if flush failed, the next func Do would send the last Do's proto.Block.
> fix/flushBuf: defer reset buf.

- .golangci.yml
- internal/ztest/logger_test.go
- proto/proto_test.go
> chore: upgrade linter

- client.go
Added `DialWithBuffer` and `ConnectWithBuffer` functions so buffer can be reused between clients and allocations reduced. This is especially useful when writing big payloads with new connections.
> feat(client): add `DialWithBuffer` and `ConnectWithBuffer` functions 

- proto/datetime64.go
- proto/time.go
- proto/time_test.go
Currently time and time64 types are treated as Go's `time.Time` for inserts and scan.
This causes lots of complexity and bad UX for users.
1. We have to deal with Day, Month and Year eventhough that is not part of original CH time and time64 types
2. Handling timezone. Which is also not part of CH types.
Having coming up with "sane" zero values is super cumbersome. Plus it's going to be bad UX for developers if want to do some arithmetic on those types.
This PR converts that to more sane `time.Duration` type. This type fits naturally to CH time and time64 types.
[
Also see this comment](https://github.com/ClickHouse/clickhouse-go/pull/1669/files#r2398218310)
> feat(time): Replace `time.Time` with `time.Duration` for Go type
